chore:ci: refactor

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -1,45 +1,47 @@
-# https://taskfile.dev
+# https://taskfile.dev/#/installation
 
 # To use this Taskfile on Windows, add Git\bin (or git\usr\bin) to PATH.
 # This allows using Git's sh.exe to run posix shell commands.
 #
 # To add git to the path just for the current powershell session:
 #* $Env:Path += ";$Env:ProgramFiles\Git\bin";
-#
-# Dependencies:
-#* git: https://git-scm.com/downloads
-#* go: https://golang.org/doc/install (>=1.21)
-#* goreleaser: https://goreleaser.com/install/
-#* nodejs: https://nodejs.org/en/download/ (LTS 20)
-#* pnpm: https://pnpm.io/installation
-#* task: https://taskfile.dev/#/installation
 
 version: "3"
-
 tasks:
   ##### CI #####
   build:frontend:
     desc: Build front-end
-    dir: ./memos-upstream
-    # silent: true
-    cmds:
-      # install dependencies
-      - cd ./web && pnpm i --frozen-lockfile
-      # generate typescript types from protobuf files using type-gen script; fallback to buf generate
-      - (cd ./web && pnpm type-gen) || (cd ./proto && buf generate)
-      # remove leftovers from previous local builds
-      - sh -c "rm -rf ./web/dist"
-      - sh -c "rm -rf ../build/dist"
-      # build front-end
-      - cd ./web && time pnpm build
-      # move front-end build to top-level build/dist
-      - sh -c "( mv -f ./web/dist ../build/ ) || ( sleep 2 && mv -f ./web/dist ../build/ )"
+    dir: ./memos-upstream/web
+    vars:
+      SRC: ./dist
+      DST: ../../build
     sources:
-      - ./web/src/**/*
-      - ./web/pnpm-lock.yaml
+      - ./src/**/*
+      - ./pnpm-lock.yaml
     generates:
-      - ../build/dist/**/*
-  
+      - "{{.DST}}/dist/**/*"
+    cmds:
+      - silent: true
+        cmd: |
+          sh -c '
+            echo -e "\e[36mCleaning up leftovers...\e[0m"
+            rm -rf "{{.SRC}}"
+            rm -rf "{{.DST}}/{{.SRC}}"
+            mkdir -p "{{.DST}}"
+          '
+      - pnpm i --frozen-lockfile
+      - pnpm type-gen
+      - pnpm build
+      - silent: true
+        cmd: |
+          echo -e "\e[36mMoving front-end build...\e[0m"
+          sh -c 'mv -f "{{.SRC}}" "{{.DST}}"'
+          if ! [ -d "{{.DST}}" ]; then
+            echo -e "\n\e[31m>> Front-end build failed! <<\e[0m"
+            exit 1
+          fi
+          echo -e "\n\e[32m>> Front-end build succeeded. <<\e[0m"
+
   build:backend-tidy:
     desc: Tidy backend dependencies
     dir: ./memos-upstream
@@ -53,46 +55,46 @@ tasks:
     summary: |
       - Create compressed archives containing built binaries and dist folder
       Goreleaser doesn't compress snapshot builds, so we do it manually.
-    silent: true
     deps:
       - build:frontend
     cmds:
-      - |
-        for dir in ./build/backend/memos*; do
-          if ! [ -d "$dir" ]; then
-            continue
-          fi
-
-          sh -c "rm -rf ${dir//\\//}/dist"
-          sh -c "( mv -f ./build/dist ${dir//\\//}/ ) || ( sleep 2 && mv -f ./build/dist ${dir//\\//}/ )"
-
-          filename=$(sh -c "basename ${dir//\\//}")
-          echo "Compressing $filename..."
-
-          ok=false
-          if [[ $filename == *"windows"* ]]; then
-            if ! [ -z $(command -v 7za) ]; then
-              sh -c "cd ${dir//\\//}; 7za -tzip a ../../$filename.zip *" > /dev/null
-              ok=true
-            elif ! [ -z $(command -v zip) ]; then
-              sh -c "cd ${dir//\\//}; zip -r ../../$filename.zip *" > /dev/null
-              ok=true
-            elif ! [ -z $(command -v powershell) ]; then
-              powershell -Command "Compress-Archive -Force -Path ${dir//\\//}/* -DestinationPath ./build/$filename.zip"
-              ok=true
-            elif ! [ -z $(command -v pwsh) ]; then
-              pwsh -Command "Compress-Archive -Force -Path ${dir//\\//}/* -DestinationPath ./build/$filename.zip"
-              ok=true
+      - silent: true
+        cmd: |
+          for dir in ./build/backend/memos*; do
+            if ! [ -d "$dir" ]; then
+              continue
             fi
-          fi
 
-          if ! $ok; then
-            sh -c "cd ${dir//\\//}; tar -czf $filename.tar.gz *"
-            sh -c "mv -f ${dir//\\//}/$filename.tar.gz ./build/$filename.tar.gz"
-          fi
+            sh -c "rm -rf ${dir//\\//}/dist"
+            sh -c "( mv -f ./build/dist ${dir//\\//}/ ) || ( sleep 2 && mv -f ./build/dist ${dir//\\//}/ )"
 
-          sh -c "( mv -f ${dir//\\//}/dist ./build/ ) || ( sleep 2 && mv -f ${dir//\\//}/dist ./build/ )"
-        done
+            filename=$(sh -c "basename ${dir//\\//}")
+            echo -e "\e[36mCompressing $filename...\e[0m"
+
+            error=1
+            if [[ $filename == *"windows"* ]]; then
+              if ! [ -z $(command -v 7za) ]; then
+                sh -c "cd ${dir//\\//}; 7za -tzip a ../../$filename.zip *" > /dev/null
+                error=$?
+              elif ! [ -z $(command -v zip) ]; then
+                sh -c "cd ${dir//\\//}; zip -r ../../$filename.zip *" > /dev/null
+                error=$?
+              elif ! [ -z $(command -v powershell) ]; then
+                powershell -Command "Compress-Archive -Force -Path ${dir//\\//}/* -DestinationPath ./build/$filename.zip"
+                error=$?
+              elif ! [ -z $(command -v pwsh) ]; then
+                pwsh -Command "Compress-Archive -Force -Path ${dir//\\//}/* -DestinationPath ./build/$filename.zip"
+                error=$?
+              fi
+            fi
+
+            if [[ $error -ne 0 ]]; then
+              sh -c "cd ${dir//\\//}; tar -czf $filename.tar.gz *"
+              sh -c "mv -f ${dir//\\//}/$filename.tar.gz ./build/$filename.tar.gz"
+            fi
+
+            sh -c "( mv -f ${dir//\\//}/dist ./build/ ) || ( sleep 2 && mv -f ${dir//\\//}/dist ./build/ )"
+          done
     sources:
       - ./build/backend/memos-*/**/*
     generates:
@@ -119,7 +121,7 @@ tasks:
 
   build:snapshot:all:
     desc: Build binaries for ALL configured OS/Arch, ignores git status
-    summary: &snapshot-summary | 
+    summary: &snapshot-summary |
       Snapshot builds bumps the patch version and appends -dev to the version string.
     deps: &snapshot-deps
       - build:backend-tidy
@@ -127,8 +129,8 @@ tasks:
     sources: &snapshot-sources
       - ./.goreleaser-snapshot.yaml
       - ./memos-upstream/**/*.go
-      - ./memos-upstream/**/go.mod
-      - ./memos-upstream/**/go.sum
+      - ./memos-upstream/**/go.{mod,sum}
+      - ./memos-upstream/proto/**/*      
     generates: &snapshot-generates
       - ./build/backend/memos*/memos*
       - ./build/*.{zip,tar.gz}
@@ -158,7 +160,7 @@ tasks:
     deps:
       - build:backend-tidy
       - build:frontend
-    cmds:      
+    cmds:
       - goreleaser build --clean --single-target
 
   build:all:
@@ -182,42 +184,85 @@ tasks:
     cmds:
       - goreleaser release --clean --timeout 60m
 
-  cleanrepo:
-    desc: Cleanup all local changes
-    ignore_error: true
+  clean:
+    desc: Clean-up all build artifacts
     cmds:
-      - sh -c "rm -rf ./build"
-      - sh -c "rm -rf ./memos-upstream/web/node_modules"
-      - sh -c "rm -rf ./memos-upstream/web/dist"
-      - sh -c "rm -rf ./memos-upstream/server/frontend/dist"
-      - sh -c "mv -f ./memos-upstream/server/frontend/dist.bak ./memos-upstream/server/frontend/dist"  
+      - for:
+          - "./build"
+          - "./memos-upstream/web/node_modules"
+          - "./memos-upstream/web/dist"
+          - "./memos-upstream/server/frontend/dist"
+          - "./memos-upstream/server/frontend/dist.bak"
+        cmd: sh -c 'rm -rf "{{ .ITEM }}"'
+
   ##### /Local #####
 
-  ##### Git-related #####
-  subtree:checkout-latest:
-    desc: Checkout Memos subtree to latest commit.
+  default:
+    silent: true
+    preconditions:
+      - sh: "! [ -z $(command -v sh) ]"
+        msg: "sh not found. Please install git from https://git-scm.com/downloads and add it to PATH."
+      - sh: "! [ -z $(command -v go) ]"
+        msg: |
+          go not found. Please install it from https://golang.org/doc/install
+          If it's installed with gobrew or similar, make sure to run `gobrew use` before running this task.
+      - sh: "! [ -z $(command -v goreleaser) ]"
+        msg: "goreleaser not found. Please install it from https://goreleaser.com/install/"
+      - sh: "! [ -z $(command -v node) ]"
+        msg: |
+          node not found. Please install version 20 from https://nodejs.org/en/download/
+          If it's installed with nvm or similar, make sure to run `nvm use 20` before running this task.
+      - sh: "! [ -z $(command -v pnpm) ]"
+        msg: "pnpm not found. Please install it from https://pnpm.io/installation"
+      - sh: "! [ -z $(command -v buf) ]"
+        msg: "buf not found. Please install it from https://docs.buf.build/installation"
     cmds:
-      - git subtree pull --prefix=memos-upstream https://github.com/usememos/memos.git main --squash
-  
-  subtree:checkout-tag:
+      - echo -e "\e[36mAll requirements are met.\e[0m\n"
+      - task --list
+
+  ##### Git-related #####
+  git:reset:
+    desc: Reset main branch to origin/main
+    prompt: |-
+      This will exclude ALL untracked files and changes on the working tree,
+      reseting the local repo to origin/main.
+      Are you sure?
+    cmds:
+      - git fetch origin
+      - git checkout main
+      - git reset --hard origin/main
+      - git clean -fdx
+      - git checkout -
+
+  git:subtree:pull-latest:
     desc: |
-      Checkout Memos subtree to supplied tag.
-      Usage: `task subtree:checkout-tag -- v0.0.0`.
+      Pull latest commit from Memos subtree.
+      Note: requires a clean git state. `memos-upstream` folder will be reset.
+    cmds:
+      - git subtree pull --prefix=memos-upstream https://github.com/usememos/memos.git main --squash --message="Checkout memos-upstream to latest commit"
+      - git reset -fx memos-upstream
+
+  git:subtree:pull-tag:
+    desc: |
+      Pull a specific tag from Memos subtree.
+      Usage: `task git:subtree:pull-tag -- v0.0.0`.
+      Note: requires a clean git state.
     cmds:
       - git subtree pull --prefix=memos-upstream https://github.com/usememos/memos.git tags/{{.CLI_ARGS}} --squash --message="Checkout memos-upstream to {{.CLI_ARGS}}"
+      - git reset -fdx memos-upstream
 
-  subtree:reset:
+  git:subtree:reset:
     desc: Reset subtree.
     cmds:
-      - sh -c "rm -rf ./memos-upstream || true"
+      - sh -c "rm -rf ./memos-upstream"
       - git rm -fr memos-upstream --ignore-unmatch
       - git commit -m "Remove memos-upstream subtree"
-      - git subtree add --prefix=memos-upstream https://github.com/usememos/memos.git main --squash --message="Init memos-upstream subtree"
+      - git subtree add --prefix=memos-upstream https://github.com/usememos/memos.git main --squash --message="Reset memos-upstream subtree"
 
-  pushtag:
+  git:tag:push:
     desc: |
       Checkout subtree to supplied tag and push a new tag to origin.
-      Usage: `task pushtag -- v0.0.0`.
+      Usage: `task git:tag:push -- v0.0.0`.
     summary: |
       This will trigger the GitHub Action to build and release the binaries.
     cmds:
@@ -226,10 +271,10 @@ tasks:
       - git tag -a {{.CLI_ARGS}} -m "Push {{.CLI_ARGS}}"
       - git push origin {{.CLI_ARGS}}
 
-  deletetag:
+  git:tag:delete:
     desc: |
       Delete a git tag.
-      Usage: `task deletetag -- v0.0.0`.
+      Usage: `task git:tag:delete -- v0.0.0`.
     summary: |
       Used in case the CI pipeline fails and some correction is needed.
 
